org.gradle.jvmargs=-Xmx2G
# Gradle of this loader does not run on Java 26 yet
org.gradle.java.home=D:/apps/intellij/jdk/25
org.gradle.parallel=true
org.gradle.configuration-cache=false

# NeoForge Properties
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.22-beta

# Mod Properties
mod_version=1.1.0+26.3
mod_group_id=me.avie29.tabbylib
mod_id=tabbylib
