org.gradle.jvmargs=-Xmx2G
# Gradle of this loader does not run on Java 26 yet
org.gradle.java.home=D:/apps/intellij/jdk/25
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

# Forge Properties
minecraft_version=26.1
minecraft_version_range=[26.1]
forge_version=62.0.9
forge_version_range=[62,)

# Mod Properties
mod_version=1.1.0+26.1
mod_group_id=me.avie29.tabbylib
mod_id=tabbylib
