org.gradle.jvmargs=-Xmx2G
# Gradle of this loader does not run on Java 26 yet
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot
org.gradle.parallel=true
org.gradle.configuration-cache=false

# NeoForge Properties
minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.15-beta

# Mod Properties
mod_version=1.0.0+26.1.1
mod_group_id=me.avie29.tabbylib
mod_id=tabbylib
