{
  "formatVersion": "1.1",
  "component": {
    "group": "me.avie29.tabbylib",
    "module": "tabbylib-neoforge",
    "version": "1.0.0+26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tabbylib-neoforge-1.0.0+26.1.1.jar",
          "url": "tabbylib-neoforge-1.0.0+26.1.1.jar",
          "size": 615001,
          "sha512": "142c1cda3eeb1ae533ff15cbb539f96bb56c7b05c6fdb01985a8c1380c4e89e61a4b7e34fe6dfb29487239521556dba4dc3e30ba39342a78bcb5fb878cbd1128",
          "sha256": "ac15c8c54cee214beaa1b0a0d9e33bf9ce0a48284278f8b101c0d2ae3018442e",
          "sha1": "64d3f8fb91fe049a0fc2706f733c076722fcd26d",
          "md5": "76f095761593c84f9e05d2e78cd96f15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tabbylib-neoforge-1.0.0+26.1.1.jar",
          "url": "tabbylib-neoforge-1.0.0+26.1.1.jar",
          "size": 615001,
          "sha512": "142c1cda3eeb1ae533ff15cbb539f96bb56c7b05c6fdb01985a8c1380c4e89e61a4b7e34fe6dfb29487239521556dba4dc3e30ba39342a78bcb5fb878cbd1128",
          "sha256": "ac15c8c54cee214beaa1b0a0d9e33bf9ce0a48284278f8b101c0d2ae3018442e",
          "sha1": "64d3f8fb91fe049a0fc2706f733c076722fcd26d",
          "md5": "76f095761593c84f9e05d2e78cd96f15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tabbylib-neoforge-1.0.0+26.1.1-sources.jar",
          "url": "tabbylib-neoforge-1.0.0+26.1.1-sources.jar",
          "size": 530379,
          "sha512": "a31f30f0c8d168b7a1b920728404397676b49841e92e634348b7e30599cfd1da89ccc1f78af72c9a9a92a6d656be3886f1cdef51d1a776cb37903eb0921ebb15",
          "sha256": "20392475bcace609788144e37ff6d7d968e99d25fe92371ce106b1df8b5ff65a",
          "sha1": "a34e1b16926449c91d14b5b4ae4e74b19bc7c8f8",
          "md5": "25604e24c100c0d8d2ff9b527fc778e3"
        }
      ]
    }
  ]
}
