modLoader="javafml"
loaderVersion="[1,)"
license="CC-BY-NC-4.0"
showAsDataPack=false

[[mixins]]
config="tabbylib.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="TabbyLib"
authors="Avie29"
description='''Config Library for Avies Mods'''
logoFile="icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
