modLoader="javafml"
loaderVersion="[1,)"
license="CC-BY-NC-4.0"
showAsDataPack=false
issueTrackerURL="https://github.com/avie293/tabbylib/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="TabbyLib"
authors="Avie29"
description='''Config Library for Avies Mods'''
logoFile="assets/tabbylib/icon.png"
displayURL="https://avie29.me/"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
