{
  "formatVersion": "1.1",
  "component": {
    "group": "me.avie29.tabbylib",
    "module": "tabbylib-forge",
    "version": "1.0.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tabbylib-forge-1.0.0+26.1.jar",
          "url": "tabbylib-forge-1.0.0+26.1.jar",
          "size": 615408,
          "sha512": "e6c7e68a79c702a272f3b16ab17d87b3c234903ef085a3a7053f0f6569eafa61558f2119ba4bc68843249f0851ea993f2e70e68d4e81c8ff660a23dd35150e4f",
          "sha256": "26b401684da536416effd0cdb4f1b5970c0f3a468de44824754bed9c65e21953",
          "sha1": "166292bb5db01f75cf29d6a9d8fb2e6683783f2b",
          "md5": "211ad5c342faef678f8ebecb3ef50041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "26.1-62.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "tabbylib-forge-1.0.0+26.1.jar",
          "url": "tabbylib-forge-1.0.0+26.1.jar",
          "size": 615408,
          "sha512": "e6c7e68a79c702a272f3b16ab17d87b3c234903ef085a3a7053f0f6569eafa61558f2119ba4bc68843249f0851ea993f2e70e68d4e81c8ff660a23dd35150e4f",
          "sha256": "26b401684da536416effd0cdb4f1b5970c0f3a468de44824754bed9c65e21953",
          "sha1": "166292bb5db01f75cf29d6a9d8fb2e6683783f2b",
          "md5": "211ad5c342faef678f8ebecb3ef50041"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tabbylib-forge-1.0.0+26.1-sources.jar",
          "url": "tabbylib-forge-1.0.0+26.1-sources.jar",
          "size": 530532,
          "sha512": "6473d418f922f9b9f5808aa74574cf181a1dbbbb20750f2ea37be91dd710752ee5b93e8f342056b0e76db75dc9ce2e432d78b6e0be68249f68ccb1036840448f",
          "sha256": "0d99c9be1f847deb5d4aab7fd975a966dd0c98bccea3f2bbfea0a45709443187",
          "sha1": "14de30076c0a8cad2cd1b6447815d4f50aa846b7",
          "md5": "aba7f9deafa2b3ab06719db99f6edd05"
        }
      ]
    }
  ]
}
